In [2]:
#2d list using for loop

f = [[j for j in range(5,10)] for i in range(4)]
print(f)

[[5, 6, 7, 8, 9], [5, 6, 7, 8, 9], [5, 6, 7, 8, 9], [5, 6, 7, 8, 9]]


In [3]:
#2d list using FOR loop user input

n = int(input("Enter no of rows"))
m = int(input("Enter no of columns"))

l = [[j for j in range(n)] for j in range(m)]

print(l)

Enter no of rows5
Enter no of columns6
[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [13]:
#ADD
l1 = [[1,2,3],[4,5,6]]
l2 = [[7,8,9],[10,11,12]]

for i in range(2):
    for j in range(3):
        l1[i][j]+= l2[i][j]
l1


[[8, 10, 12], [14, 16, 18]]

In [14]:
#SUB
l1 = [[1,2,3],[4,5,6]]
l2 = [[7,8,9],[10,11,12]]

for i in range(2):
    for j in range(3):
        l1[i][j]-= l2[i][j]
l1

[[-6, -6, -6], [-6, -6, -6]]

In [15]:
#MULTIPLY
l1 = [[1,2,3],[4,5,6]]
l2 = [[7,8,9],[10,11,12]]

for i in range(2):
    for j in range(3):
        l1[i][j]*= l2[i][j]
l1

[[7, 16, 27], [40, 55, 72]]

In [10]:
print(l1[1][2])
print(l2[0:2])

6
[[7, 8, 9], [10, 11, 12]]


In [26]:
n = int(input())
for i in range(1,n+1):
    for j in range(1,i+1):
        print(j,end='')
        
    for j in range(1,2*n-2*i+1):
        print(' ',end='')
        
    for j in range(i,0,-1):
        print(j,end='')
        
    print()    
    

5
1        1
12      21
123    321
1234  4321
1234554321


In [29]:
import numpy as np

x = np.array([4,5,6])
y = np.array([7,8,9])

print(x+y)
print(x-y)
print(x**y)
print(x/y)

[11 13 15]
[-3 -3 -3]
[   16384   390625 10077696]
[0.57142857 0.625      0.66666667]


In [33]:
import pandas as pd

path = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"

df = pd.read_csv(path, header = None)

In [34]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [35]:
df.tail()

0      1     2     3     4    5     6     7     8     9     10    11  \
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.7  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.3  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.2  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.3  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.2  0.61   

       12   13  
173  1.74  740  
174  1.56  750  
175  1.56  835  
176  1.62  840  
177  1.60  560